# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias zk0='$KAFKA_HOME/bin/zookeeper-server-start.sh $KAFKA_HOME/config/zookeeper0.properties'
alias kk0='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server0.properties'
alias kk1='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server1.properties'
alias kk2='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server2.properties'
alias kk3='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server3.properties'
alias kk4='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server4.properties'
alias kk5='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server5.properties'
alias kk6='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server6.properties'
alias kk7='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server7.properties'
alias kk8='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server8.properties'
alias kk9='$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server9.properties'
alias kkstop='$KAFKA_HOME/bin/kafka-server-stop.sh'
alias kkprod='$KAFKA_HOME/bin/kafka-console-producer.sh --broker-list'
alias kkcosm='$KAFKA_HOME/bin/kafka-console-consumer.sh --bootstrap-server'
alias zkstop='$KAFKA_HOME/bin/zookeeper-server-stop.sh'
alias nifi='$NIFI_HOME/bin/nifi.sh'
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
export KAFKA_HOME='/home/kienpham/kafka'
export NIFI_HOME='/home/kienpham/nifi'
export JAVA_HOME='/usr/lib/jvm/jre-1.8.0-openjdk'
# User specific aliases and functions
